### PR TITLE
Get all ansi escape sequences

### LINKED ISSUE #14: Slice fails when ANSI string and ordinary string are mixed
[Issuehunt badges](https://issuehunt.io/r/chalk/slice-ansi/issues/14)

Hello, the following behaviors looked like a bug.

```
node
> chalk = require('chalk')
> sliceAnsi = require('slice-ansi')
> str = 'a' + chalk.red('bc') + 'd'
'a\u001b[31mbc\u001b[39md'
> sliceAnsi(str, 0, 1) === 'a'
false  # I expected true
> sliceAnsi(str, 1, 2) === chalk.red('b')
true
> sliceAnsi(str, 2, 3) === chalk.red('c')
false  # I expected true
> sliceAnsi(str, 3, 4) === 'd'
false  # I expected true
```

As a supplement, the example described in the README appeared to be working properly.

```
node
> str2 = 'The quick brown ' + chalk.red('fox jumped over ') + 'the lazy ' + chalk.green('dog and then ran away with the unicorn.');
'The quick brown \u001b[31mfox jumped over \u001b[39mthe lazy \u001b[32mdog and then ran away with the unicorn.\u001b[39m'
> sliceAnsi(str2, 20, 30) === chalk.red('jumped ove')
true
```

Thanks.

### Environments
- node v6.8.0
- chalk v2.3.0
- slice-ansi v1.0.0

> There is a $60.00 open bounty on this issue. Add more on [Issuehunt](https://issuehunt.io/r/chalk/slice-ansi/issues/14).
> - Checkout the [Issuehunt explorer](https://issuehunt.io/r/chalk/slice-ansi/) to discover more funded issues.
> - Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on Issuehunt to raise funds.

### LINKED ISSUE #22: Fails with strings styled with background and foreground
[Issuehunt badges](https://issuehunt.io/r/chalk/slice-ansi/issues/22)

PR for a demo test: #21 

Looks like slicing a string styled with background and foreground colors fails.

```js
const str = chalk.bgGreen.black('test');
// => '\u001b[42m\u001b[30mtest\u001b[39m\u001b[49m'

const sliced = sliceAnsi(str, 0, 1);
// => '\u001b[42m\u001b[30mt\u001b[39m'

const full = sliceAnsi(str, 0, 4)
// => '\u001b[42m\u001b[30mtest\u001b[39m\u001b[49m'
```

I'm not super familiar with ansi escape sequences but it looks like `sliced` is missing the part that ends the `bgGreen` color, `'\u001b[49m'`.

---

Failing test:

https://github.com/chalk/slice-ansi/blob/67699dedbdf3bbe7b05678bf3665baab8f62d9c4/test.js#L61-L65

> There is a $60.00 open bounty on this issue. Add more on [Issuehunt](https://issuehunt.io/r/chalk/slice-ansi/issues/22).
> - Checkout the [Issuehunt explorer](https://issuehunt.io/r/chalk/slice-ansi/) to discover more funded issues.
> - Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on Issuehunt to raise funds.

### LINKED ISSUE #24: Adds extra escape when there's a space at the end
[Issuehunt badges](https://issuehunt.io/r/chalk/slice-ansi/issues/24)

For some reason when there's a space or multiple spaces at the end, `slice-ansi` adds closing escape (`\u001b[39m`) at the end of the string. I opened https://github.com/chalk/slice-ansi/pull/23 with a failing test, which consistently reproduces the issue.

> There is a $80.00 open bounty on this issue. Add more on [Issuehunt](https://issuehunt.io/r/chalk/slice-ansi/issues/24).
> - Checkout the [Issuehunt explorer](https://issuehunt.io/r/chalk/slice-ansi/) to discover more funded issues.
> - Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on Issuehunt to raise funds.

### PR DESCRIPTION
**Pull request by TiagoDanin**
# Summary: 
- Replace default end code `39m` ~> `0m` (Work with "true color", background & foreground)
- Sort end codes
- Work with background
- Work with "true color"
- Fix "true color" test
- Remove ansi code at the end not used

# Fix
Closes #14
Closes #22
Closes #24

### CODE REVIEW

**Comment by TiagoDanin** [comment]
@sindresorhus Could you review this PR ?

**Comment by Qix-** [comment]
> Replace default end code 39m ~> 0m (Work with "true color", background & foreground)q

Why? 0m also resets all other modes, which is not the SE functionality. 39 works with truecolor just fine. If you want to reset the background, also specify 49.

**Comment by TiagoDanin** [comment]
@Qix- Only returns `0m` in case you don't find the end code.
https://github.com/chalk/slice-ansi/blob/71f382bc0bd13c1fa1f0a4139ece40f2d3ce63e5/index.js#L63

**Comment by Qix-** [comment]
@TiagoDanin You can change it to just `m`. `0m` is redundant.

**Comment by TiagoDanin** [comment]
Did you see the diff? All and True Color is closed with correct end codes ([test](https://github.com/chalk/slice-ansi/pull/25/files#diff-1dd241c4cd3fd1dd89c570cee98b79ddR74))

If `ansiStyles.codes.get(parseInt(ansiColor, 10))` fails, the return will be `0m` ([Previously `39m`](https://github.com/chalk/slice-ansi/pull/25/files#diff-168726dbe96b3ce427e7fedce31bb0bcL51)).

**Comment by Qix-** [comment]
But my point is `39m` works with true color.

**Comment by TiagoDanin** [comment]
Examples:
- Current: `sliceAnsi("\u001B[1m\u001B[48;2;255;255;255mABC", 0, 2) // Failure and returns 39m` - Visual impact

- New: `sliceAnsi("\u001B[1m\u001B[48;2;255;255;255mABC", 0, 2) // Success and returns 22m, 49m` - No visual impact

- New (If had failed): `sliceAnsi("\u001B[1m\u001B[48;2;255;255;255mABC", 0, 2) // Failure and returns 0m` - No visual impact

A comparison with 39m vs 0m

39m | 0m |
------ | ---- |
Finalize only foreground color | Finalize all colors |
Do not work with background | Work with background |
Do not work with style modifiers | Work with style modifiers |

**NOTE¹**: There is background in true color (`39m` is not valid).
**NOTE²**: `0m` is best option in case of failures

**Comment by Qix-** [comment]
I'm quite lost as to what you mean.

`39m` is "reset foreground color". It works with the `38;2;r;g;bm` code just fine. The same for `48;2;...m` and `49m`.

What is it you're claiming does not work?

**Comment by TiagoDanin** [comment]
> What is it you're claiming does not work?

Nothing! See the tests

## Old
(`39m` will **only** work with foreground).
 
In https://github.com/chalk/slice-ansi/blob/865b0d68a309d4ade7f5100b417ab5f00ed53af8/index.js#L51 if the `ansiStyles.codes.get(parseInt(escapeCode, 10))` returns `undefined`.

in https://github.com/chalk/slice-ansi/blob/865b0d68a309d4ade7f5100b417ab5f00ed53af8/index.js#L51 wrapAnsi is calling with value `END_CODE` (`END_CODE === 39`).

## New
(`0m` work with all)

In https://github.com/chalk/slice-ansi/blob/71f382bc0bd13c1fa1f0a4139ece40f2d3ce63e5/index.js#L57, if the `ansiStyles.codes.get(parseInt(ansiColor, 10))` returns `undefined`.

in https://github.com/chalk/slice-ansi/blob/71f382bc0bd13c1fa1f0a4139ece40f2d3ce63e5/index.js#L67 wrapAnsi is calling with value `0`

File: test.js [hunk 1]
```diff
@@ -50,18 +50,18 @@ test('doesn\'t add unnecessary escape codes', t => {
...
 
-test.failing('can slice a normal character before a colored character', t => {
+test('can slice a normal character before a colored character', t => {
 	t.is(sliceAnsi('a\u001B[31mb\u001B[39m', 0, 1), 'a');
 });
 
-test.failing('can slice a normal character after a colored character', t => {
-	t.is(sliceAnsi('\u001B[31ma\u001B[39mb', 1, 2), 'b');
+test('can slice a normal character after a colored character', t => {
+	t.is(sliceAnsi('\u001B[31ma\u001B[39mb', 1, 2), '\u001B[31m\u001B[39mb');
```
Comment (sindresorhus) [inline test.js]: Why did you change the test? The correct result is `b`. We should not output moot ansi escapes.

File: index.js [hunk 2]
```diff
@@ -44,11 +46,26 @@ module.exports = (string, begin, end) => {
...
 		if (visible > begin && visible <= end) {
 			output += character;
-		} else if (visible === begin && !isInsideEscape && escapeCode !== undefined && escapeCode !== END_CODE) {
-			output += wrapAnsi(escapeCode);
+		} else if (visible === begin && !isInsideEscape && ansiCode !== undefined) {
+			output += wrapAnsi(ansiCode);
 		} else if (visible >= end) {
-			if (escapeCode !== undefined) {
-				output += wrapAnsi(ansiStyles.codes.get(parseInt(escapeCode, 10)) || END_CODE);
+			for (let aansiCode of ansiCodes) {
```
Comment (sindresorhus) [inline index.js]:
```suggestion
			for (let ansiCode of ansiCodes) {
```

File: test.js [hunk 3]
```diff
@@ -50,18 +50,18 @@ test('doesn\'t add unnecessary escape codes', t => {
...
 });
 
 // See https://github.com/chalk/slice-ansi/issues/22
-test.failing('can slice a string styled with both background and foreground', t => {
+test('can slice a string styled with both background and foreground', t => {
 	// Test string: `chalk.bgGreen.black('test');`
-	t.is(sliceAnsi('\u001B[42m\u001B[30mtest\u001B[39m\u001B[49m', 0, 1), '\u001B[42m\u001B[30mt\u001B[39m\u001B[49m');
+	t.is(sliceAnsi('\u001B[42m\u001B[30mtest\u001B[39m\u001B[49m', 0, 1), '\u001B[42m\u001B[30mt\u001B[49m\u001B[39m');
```
Comment (sindresorhus) [inline test.js]: The order of end escapes should be preserved.

**Comment by sindresorhus** [comment]
> NOTE²: 0m is best option in case of failures

What are "failures"? When would that occur. I also don't see any added tests for when `0m` is used. Can you add that?

File: test.js (hunk 3 above)
Comment (TiagoDanin) [reply test.js]: :+1:

File: test.js (hunk 1 above)
Comment (TiagoDanin) [reply test.js]: Because of the "main" test, it has the same problem (`\u001B[32m\u001B[39m`).
https://github.com/chalk/slice-ansi/blob/e33482c0288c56fb958bd68fd6f81527cd04bb3a/test.js#L28
But I'm going to fix it :)

**Comment by sindresorhus** [comment]
Nice work! :)

**Comment by sindresorhus** [comment]
@TiagoDanin Since you're deep into ansi escape codes now, maybe you wanna also do https://github.com/chalk/wrap-ansi/issues/35 ;)
