### PR TITLE
Don't escape while in another escape

### LINKED ISSUE #6: Adds moot escape codes
``` js
sliceAnsi('\u001b[31municorn\u001b[39m', 0, 3);
//=> '\u001b[31m\u001b[31m\u001b[31m\u001b[31m\u001b[31muni\u001b[39m'
```

Notice how it prepends a lot of moot `\u001b[31m` to the output.

I added a failing skipped test: https://github.com/chalk/slice-ansi/commit/f725d7677cb8b734f63b39fbbabd7261fe3be821
## 

// @dthree

### PR DESCRIPTION
**Pull request by kevva**
Fixes #6.

### CODE REVIEW

File: test.js [hunk 1]
```diff
@@ -25,8 +25,8 @@ test(t => {
 		}
 	}
 
-	const a = util.inspect('\u001B[31m\u001B[31m\u001B[31m\u001B[31m\u001B[31mthe \u001B[39m\u001B[32mquick \u001B[39m\u001B[34m\u001B[39m');
-	const b = util.inspect('\u001B[32m\u001B[39m\u001B[39m\u001B[39m\u001B[39m\u001B[39m\u001B[34m\u001B[34m\u001B[34m\u001B[34m\u001B[34mbrown \u001B[39m\u001B[36mfox \u001B[39m\u001B[33m\u001B[39m');
+	const a = util.inspect('\u001B[31mthe \u001B[39m\u001B[32mquick \u001B[39m\u001B[34m\u001B[39m');
+	const b = util.inspect('\u001B[32m\u001B[39m\u001B[34mbrown \u001B[39m\u001B[36mfox \u001B[39m\u001B[33m\u001B[39m');
```
Comment (kevva) [inline test.js]: Seems like these we're adopted to make the bug pass.

**Comment by sindresorhus** [comment]
Oh wow. So productive 🙌
